services:
  main:
    build:
      context: .
      dockerfile: dockerfile
    image: aperol
    command: uvicorn amo.server:app --host 0.0.0.0 --port 8080
    ports:
      - "8050:8080"
    volumes:
      - ./amo:/app/amo
      - ./config:/app/config
      - ./core:/app/core
      - ./services:/app/services
      - ./utils:/app/utils
      - ./logs:/app/logs
      - ./photos:/app/photos
